services:
  ai-english-backend:
    container_name: ai-english-backend
    build: ./backend
    ports:
      - "3000:3000"
      - "9300:9300"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=file:./data/usagedb.sqlite
      - CACHE_DATABASE_URL=file:./data/cachedb.sqlite

  ai-english-frontend:
    container_name: ai-english-frontend
    build: ./frontend
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - ai-english-backend
